# Usage: save your github_token in github_token.txt
# docker build -t sglang:xpu_u2410 -f  Dockerfile.xpu --no-cache .


# default base image
ARG BASE_IMAGE="xpu_pvc:base"

FROM $BASE_IMAGE AS base
USER root

# Set environment variables

ARG SG_LANG_REPO=https://github.com/sgl-project/sglang.git
ARG SG_LANG_BRANCH=main

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHON_VERSION=3.10


# Set maintainer label
LABEL maintainer="zhaoqiong.zheng@intel.com"


# Install Miniforge & PyTorch/Triton & build vllm/SGlang from source to.
RUN --mount=type=secret,id=github_token \
    cd /root && \
    echo ${PYTHON_VERSION} | sed 's/\.//g' > /tmp/version.txt && \
    export PYTHON_VERSION_STRING=$(cat /tmp/version.txt) && \
    . /miniforge3/bin/activate && \
    conda activate py${PYTHON_VERSION_STRING} && \
    # Install vllm from source
    cd /root && \
    . /opt/intel/oneapi/setvars.sh && \
    echo "Building vllm/sglang from source ..." && \
    git clone https://github.com/zhuyuhua-v/vllm.git && \
    cd vllm && \
    git checkout yuhua/deepseek && \
    pip install setuptools_scm --root-user-action=ignore && \
    pip install setuptools==75.6.0 packaging==24.2 --root-user-action=ignore && \
    VLLM_TARGET_DEVICE=xpu python setup.py install && \
    # Install SGlang from source
    cd /root && \
    echo "cloning ${SG_LANG_BRANCH} from ${SG_LANG_REPO}" && \
    git clone --branch ${SG_LANG_BRANCH} --single-branch ${SG_LANG_REPO} && \
    cd sglang && \
    pip install -e "python[all_xpu]" --root-user-action=ignore && \
    # Install required packages for sglang workloads
    pip install msgspec blake3 py-cpuinfo compressed_tensors gguf partial_json_parser einops --root-user-action=ignore && \
    conda install libsqlite=3.48.0 -y && \
    echo ". /miniforge3/bin/activate; conda activate py${PYTHON_VERSION_STRING}; . /opt/intel/oneapi/setvars.sh; cd /root/" >> /root/.bashrc;


# Set the default shell to bash
SHELL ["bash", "-c"]
CMD ["bash", "-c", "source /root/.bashrc && exec bash"]
ENV PATH="/miniforge3/envs/py310/bin/python3:${PATH}"
