name: PR Test (XPU)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pr-test-xpu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if: (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') &&
      github.event.pull_request.draft == false
    runs-on: pvc-1100
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build --build-arg  \
          -t sglang-xpu-test  -f docker/Dockerfile.xpu .

      - name: Run container
        run: |
          docker run -dt \
            -e https_proxy="http://proxy-dmz.intel.com:912/" \
            -e http_proxy="http://proxy-dmz.intel.com:912/" \
            -e no_proxy=".intel.com" \
            -w /root/sglang \
            --name ci_sglang_xpu \
            sglang-xpu-test

      - name: Install Dependency
        timeout-minutes: 20
        run: |
          docker exec -w /root/sglang ci_sglang_xpu pip install pytest expecttest ray
          
      - name: Run UT Cases
        timeout-minutes: 20
        run: |
          docker exec -w /root/sglang ci_sglang_xpu pytest -v test/srt/test_custom_allreduce.py
     
      - name: Run standard tests
        timeout-minutes: 20
        run: |
          docker exec -w /root/sglang ci_sglang_xpu pytest python -m sglang.bench_one_batch --batch-size 1 --input 32 --output 32 --model deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B --trust-remote-code --device xpu
      - name: Cleanup container
        if: always() 
        run: |
          docker rm -f ci_sglang_xpu || true


  finish:
    if: always()
    needs: [build-and-test]
    runs-on: pvc-1100
    steps:
      - name: Check job status
        run: |
          if [ "${{ needs.build-and-test.result }}" != "success" ]; then
            echo "Job failed with result: ${{ needs.build-and-test.result }}"
            exit 1
          fi
          echo "All jobs completed successfully"
          exit 0
