name: PR Test (XPU)

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pr-test-xpu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if: (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') &&
      github.event.pull_request.draft == false
    runs-on: pvc-1100
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --progress=plain --secret id=github_token,src=/home/sdp/github_token.txt \
          --build-arg SG_LANG_REPO=${{ github.event.pull_request.head.repo.full_name }}  \
          --build-arg SG_LANG_BRANCH=${{ github.head_ref || github.ref_name }} \
          -f ${{ github.workspace }}/docker/Dockerfile.xpu -t sglang_xpu:u2410 .


      - name: Run container
        run: |
          docker run -dt \
            --device /dev/dri/ \
            --name ci_sglang_xpu \
            sglang_xpu:u2410

      - name: Install Dependency
        timeout-minutes: 20
        run: |
          docker exec ci_sglang_xpu /miniforge3/envs/py310/bin/python3 -m pip install --upgrade pip
          docker exec ci_sglang_xpu /miniforge3/envs/py310/bin/python3 -m pip install pytest expecttest ray

      - name: Run UT Cases
        timeout-minutes: 20
        run: |
          echo "[placeholder] UT cases"

      - name: Run standard tests
        timeout-minutes: 20
        run: |
          docker exec -w /root/sglang ci_sglang_xpu \
            /bin/bash -c "source /opt/intel/oneapi/setvars.sh && /miniforge3/envs/py310/bin/python3 -m sglang.bench_one_batch \
            --batch-size 1 \
            --input 32 \
            --output 32 \
            --model deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B \
            --trust-remote-code \
            --device xpu"

      - name: Cleanup container
        if: always()
        run: |
          docker rm -f ci_sglang_xpu || true

  finish:
    if: always()
    needs: [build-and-test]
    runs-on: pvc-1100
    steps:
      - name: Check job status
        run: |
          if [ "${{ needs.build-and-test.result }}" != "success" ]; then
            echo "Job failed with result: ${{ needs.build-and-test.result }}"
            echo "BUILD_LOG=$(cat build.log)" >> $GITHUB_ENV
            exit 1
          fi
          echo "All jobs completed successfully"
          exit 0
